Feature/164-translation
devicereg/devicereg pull request #7
Opened 2016-11-20 12:16 UTC by micken42

Ich habe mal das vue-i18n plugin in die App eingebunden und damit die Kontakt Komponente größten Teils übersetzt. Einmal bitte anschauen, ausprobieren und mergen, falls alles in Ordnung ist.

2016-11-20 15:49 UTC, Stilmittel requested changes
Super Job, Michael!
Insgesamt sieht das echt super aus :+1: 

Einzig das Naming der i18n-Keys finde ich noch nicht so ganz gelungen. Vllt. sollten wir uns da nochmal unterhalten.

Hier sind ein paar Beispiele, wie i18n in Ruby z.B. angewandt wird:
https://phraseapp.com/blog/posts/ruby-lessons-learned-naming-and-managing-rails-i18n-keys/

2016-11-20 15:49 UTC, Stilmittel commented on app/src/components/Translations.vue
> +        hello: 'Hello'
Wofür  brauchen wir das?

2016-11-20 15:49 UTC, Stilmittel commented on app/src/components/Kontakt.vue
> +        <h2>{{ $t("Kontakt.Kundensupport_fuer_Durchflussmessgeraete") }}</h2>
Punkt 1: Warum sollte der Übersetzungs-Key gleich dem deutschen Text sein?
Das macht in meinen Augen das Übersetzen schwieriger für nicht-deutschsprachige, zum Anderen sind die Keys extrem lang.

Wieso nicht einfach so etwas wie `$t("Kontakt.headline")` ?

2016-11-20 15:49 UTC, Stilmittel commented on app/src/components/Translations.vue
> +    de: {
Können wir die einzelnen Language-Files nicht auslangern in Sprachdateien?
Idealerweise hat jede Komponente für jede Sprache eine eigene JSON.

z.B. `Kontakt_de.json`, `Kontakt_en.json`

Das würde die Translations (vielleicht?) sehr viel übersichtlicher machen.

2016-11-20 15:49 UTC, Stilmittel commented on app/src/components/Translations.vue
> +  Vue.config.lang = 'en'
Warum ist die Standardsprache Englisch?

2016-11-24 12:22 UTC, micken42 commented on app/src/components/Kontakt.vue
> +        <h2>{{ $t("Kontakt.Kundensupport_fuer_Durchflussmessgeraete") }}</h2>
Ich dachte einfach nur daran, dass man so direkt erkennt was dort letzlich steht, aber mit Kontakt.ueberschrift, bzw. Contact.headline fänd ich das auch besser. Hab nicht weit genug gedacht, war so schnell dahin gerotzt. Danke für den Hinweis! :-)

2016-11-24 12:23 UTC, micken42 commented on app/src/components/Translations.vue
> +  Vue.config.lang = 'en'
Hatte ich nur gemacht, damit man sieht, was schon übersetzt wurde. Für die Entwicklung quasi. Alles was deutsch ist, muss noch übersetzt werden.

2016-11-24 12:31 UTC, micken42 commented on app/src/components/Translations.vue
> +    de: {
Jap, das könnte man so machen:

https://github.com/kazupon/vue-i18n/wiki/Usage-for-v3.0#dynamic-locale

2016-11-24 13:53 UTC, merged